// Module included in the following assemblies:
//
// * disaster_recovery/quorum-restoration.adoc

:_mod-docs-content-type: PROCEDURE
[id="dr-restoring-etcd-quorum-ha_{context}"]
= Restoring etcd quorum for high availability clusters

This procedure instantly brings back a new single-member etcd cluster based on its local data directory and marks all other members as invalid by retiring the previous cluster identifier. This procedure does not require a prior backup to restore the control plane from.

[WARNING]
====
You may experience data loss if the host that runs the restoration does not have all data replicated to it.
====

.Prerequisites

* SSH access to the node used to restore quorum.

.Procedure

. Select a control plane host to use as the recovery host. This is the host that you will run the restore operation on.

. SSH into the chosen recovery node and run the following command:
+
[source,terminal]
----
$ sudo -E /usr/local/bin/quorum-restore.sh
----

. Exit the SSH session and wait until the control plane recovers by running:
+
[source,terminal]
----
$ oc adm wait-for-stable-cluster
----
+
[NOTE]
====
If you see no progress rolling out the etcd static pods, you can force redeployment from the `cluster-etcd-operator` by running:

[source,terminal]
----
$ oc patch etcd cluster -p='{"spec": {"forceRedeploymentReason": "recovery-'"$(date --rfc-3339=ns )"'"}}' --type=merge
----
====